package com.tfg.supportbank.vistas;

import com.tfg.supportbank.dao.ClienteDao;
import com.tfg.supportbank.dos.ClienteDo;
import com.tfg.supportbank.util.ValidacionCampos;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class FormModificar extends javax.swing.JFrame {

    String cedulaCliente;
    
    public FormModificar() {
        initComponents();
    }

    FormModificar(String cedula) {
        initComponents();
        this.cedulaCliente = cedula.trim();
        findClienteByCedula();
    }

    private void findClienteByCedula() {
        ClienteDao clienteDao = new ClienteDao();
        Integer ced = Integer.valueOf(cedulaCliente);
        ClienteDo clienteDo = clienteDao.findClienteByCedula(ced);
        if (null != clienteDo){
            setFormModifyData(clienteDo);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        estadocivil = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ingresos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        empresa = new javax.swing.JTextField();
        btnModificarCliente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        segundoapellido = new javax.swing.JTextField();
        puntosDatacredito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAdjuntarCartaLaboral = new javax.swing.JButton();
        JbtnRegresar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 180, 163, 27));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Primer apellido:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 220, 163, 28));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 175, 407, -1));
        jPanel2.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 216, 407, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 300, 163, 32));
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 298, 407, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 342, 163, 31));
        jPanel2.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 339, 407, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 383, -1, 31));
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 407, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado Civil:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 424, 121, 31));

        estadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Divorciado", "Soltero", "Viudo", " ", " " }));
        estadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocivilActionPerformed(evt);
            }
        });
        jPanel2.add(estadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 421, 407, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingresos:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 465, 121, 31));

        ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosActionPerformed(evt);
            }
        });
        jPanel2.add(ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 462, 407, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Empresa:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 503, 121, 31));
        jPanel2.add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 494, 197, -1));

        btnModificarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificarCliente.setText("MODIFICAR");
        btnModificarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 169, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Segundo apellido:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 260, -1, 30));
        jPanel2.add(segundoapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 257, 407, -1));
        jPanel2.add(puntosDatacredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 541, 117, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puntos Datacredito:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 546, -1, 31));

        cedula.setEnabled(false);
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        jPanel2.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 136, 407, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cedula:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 142, 163, 25));

        jButton1.setText("Escanear Documento de Afiliacion");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 331, -1));

        btnAdjuntarCartaLaboral.setText("Adjuntar Carta Laboral");
        btnAdjuntarCartaLaboral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdjuntarCartaLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarCartaLaboralActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdjuntarCartaLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 499, 183, -1));

        JbtnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbtnRegresar.setText("< Regresar");
        JbtnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(JbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 169, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mdificar cliente.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 970, 620));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void estadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocivilActionPerformed

    private void ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresosActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        ClienteDo clienteDo = toClienteDo();        
        if (null != clienteDo){                
            ClienteDao clienteDao = new ClienteDao();
            clienteDao.updateCliente(clienteDo);
        }
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void JbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnRegresarActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_JbtnRegresarActionPerformed

    private void btnAdjuntarCartaLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarCartaLaboralActionPerformed
        UploadAndSaveFile ventanaFileChosser = new UploadAndSaveFile();
        ventanaFileChosser.setVisible(true);
    }//GEN-LAST:event_btnAdjuntarCartaLaboralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnRegresar;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton btnAdjuntarCartaLaboral;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField empresa;
    private javax.swing.JComboBox<String> estadocivil;
    private javax.swing.JTextField ingresos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField puntosDatacredito;
    private javax.swing.JTextField segundoapellido;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    private ClienteDo toClienteDo() {        
        ClienteDo clienteDo = new ClienteDo();
        List<javax.swing.JTextField> listCamposNotNull = new ArrayList<>();
        ValidacionCampos validacion = new ValidacionCampos();
       // try {
            
            Date fechaEntradaEmpresa = null;
                     
            clienteDo.setNombre(validacion.validarCamposFormString(nombre,listCamposNotNull));
            clienteDo.setApellido1(validacion.validarCamposFormString(apellido,listCamposNotNull));
            clienteDo.setApellido2(null != segundoapellido ? segundoapellido.getText(): "");
            clienteDo.setCedula(validacion.validarCamposFormLong(cedula,listCamposNotNull));
            clienteDo.setDireccion(validacion.validarCamposFormString(direccion, listCamposNotNull));
            clienteDo.setTelefono(validacion.validarCamposFormLong(telefono,listCamposNotNull));
            clienteDo.setEstadoCivil(estadocivil.getSelectedItem().toString());
            clienteDo.setEmail(validacion.validarEmail(correo,listCamposNotNull) ? correo.getText().trim() : "");
            clienteDo.setIngresos(validacion.validarCamposFormFloat(ingresos,listCamposNotNull));
            clienteDo.setEmpresa(validacion.validarCamposFormString(empresa,listCamposNotNull));
            clienteDo.setPuntosDataCredito(validacion.validarCamposFormInteger(puntosDatacredito,listCamposNotNull));
               if (listCamposNotNull.isEmpty())        
        return clienteDo;
       else {           
            JOptionPane.showMessageDialog(null, "Debe rellenar los campos Not Null"  );
            Color color=new Color(255,191,170);            
            listCamposNotNull.stream().forEach(elem -> {
                elem.setForeground(Color.BLUE);
                elem.setBackground(color);                    
                    });
            return null;
       }
    }

    private void setFormModifyData(ClienteDo clienteDo) {
        cedula.setText(String.valueOf(clienteDo.getCedula()));
        nombre.setText(clienteDo.getNombre());
        apellido.setText(clienteDo.getApellido1());
        segundoapellido.setText(clienteDo.getApellido2());
        direccion.setText(clienteDo.getDireccion());
        telefono.setText(String.valueOf(clienteDo.getTelefono()));
        estadocivil.addItem(clienteDo.getEstadoCivil());
        ingresos.setText(String.valueOf(clienteDo.getIngresos()));
        empresa.setText(clienteDo.getEmpresa());
        correo.setText(clienteDo.getEmail());
        puntosDatacredito.setText(String.valueOf(clienteDo.getPuntosDataCredito()));
        
    }
}
